{% set name = "crcmod" %}
{% set version = "1.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/crcmod-{{ version }}.tar.gz
  sha256: dc7051a0db5f2bd48665a990d3ec1cc305a466a77358ca4492826f41f283601e

build:
  # Upstream source : https://github.com/conda-forge/crcmod-feedstock/blob/2ee508ae7fb2cf562db67a5c5511c6bf2304e0a8/recipe/recipe.yaml#L16
  number: 1014
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  build:
    - python
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - crcmod
    - crcmod._crcfunext
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://crcmod.sourceforge.net/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: CRC Generator
  description: |
     Python module for generating objects that compute the Cyclic Redundancy
     Check (CRC)
  doc_url: https://crcmod.sourceforge.net/
  dev_url: https://salsa.debian.org/python-team/packages/python-crcmod

extra:
  recipe-maintainers:
    - bgruening
    - chapmanb
    - xylar
    - nehaljwani
