travis:
  secure:
    BINSTAR_TOKEN: Lx81E3V7i8rE4totr+x/ktf7wY9EfT41MbrshnpQJXXSJ33LIW87KK6gBQ/Q+OUHQvTpacgAwKyz5t81scfXEZyC1VTJbWfJGDSBZN/d5eXeHJEe5x7YPBBBpfpehs9j6EckDHeBiGxSTfQ8B1YVUpek4RaMGy4TYFbGXeStr5Nnc6g32iqgwqyl/8+ThlSlxxPaxTFs7na0koKA+R4pHAtv1fSXnO+VVMIrvo6tpRF5w/wW1FWc6GWsKxTDweCuLqjUTriM0s/vB0CdSkZW+/uMMKjwX8InSQWs5VBwTm023ml7HgCM4GCM4PRSak1KMsEYpy7tWZrlsEz3kZjgPL73oZEpWpAAbqEgi9nbetVoQtL5vaU6Vh6ihJkm6wDf/wMU0UCR7qlaRjT3JRAil/BLzEXvcTricFU04Ituaf8HI5GyISLo+/YiOwqkbjEKugPdFtLLoUqejXf2j7qp0SebUkU/dNnA1PyZ90D9xDatdoyRO4TkaNT00WI1dgmZLXfMS8EwnS1LjNNOGu4vaNBlG8A23VHrOGHsv003elzI+4fuiAsCPpqlQP7UTm+soO5aOSQFPbmWMoQsaQCOjyIO57YbC0QUO06enBMq8RqOePHjRJmrIG39CvydYwVsdQ2AOCjqoR5ywz5FrtY7hMyidW6O7RzzG7qGDhTndBM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
