appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: PN0RVYzoVRksP4ZD4AEGIFD7mmAfdU7IDdF0hG+AW4/pWTzyrA76jxn+hp+2DIpL0YOgOkMp07ZZ6xMWM2S8h0T/rurOP4WkC/4d8a5BGq2lTnUwS6arxAL60NE7tF9ggww7NvSLAVhhNxBHm6Vae/lSPa5haPwQ7LmKqLpVw+z/qKnQa9W9Vlf8ZOpyKxxHNi1wOZs+B9I4QDKttPo5bjNxuBSHHczfiwz8sKAeWrdbnhK+wCDlEfRe7kGHDxmQLXOwzHX7/xmZEZs4r2ccXRIBFPcBI9jApFYgZ4HG8PY0h8LQr6E8FUYBrI8CpqPse97MHE7kprGjtW1qCwdFOQSnp3bxUYgOR3ENrAEOKhvgS9ywslCtRDYRyJnE8/s1YRcjzWGN7uf6Iv0cAjKn+m6dzOEI849MMg+cpGFU6Mi1TjRgQlrba2GpErYfteG8aRyVyneZ2SfNMVWqU+V378bSIYVwSZF0qf12/6cRt4RkppWfFDEnm+zzeGICOea0rMyANg1t+AWspMYkEfQZLnmXkcbW3eTtRKv5aAdmyZ18t5ryO9W5ms3ef2PBfX9iEIfQcWB9JGtPkQccXn4TaaeQ/4+CklE/O7OSP5HRQRW+T2APXYR9Kb0YWULacCMkQOKG0uyD31z6c15cC53e144qnLSZmMFkaDTd2hdMnLs=}
provider:
  win: azure
conda_forge_output_validation: true
